### ISSUE TITLE
variable name should allow digits

### ISSUE THREAD

**Issue by logust79** [healeycodes/coolrule#1]
Hi Healey,
Thanks a lot for the nice work!

However though the code panics when a variable has digits in it. e.g.
```
expr = coolrule::new("x1 >= 5");
```
And it will panic
```
x1 > 5
^ seq [40] expect: 40, found: 120
```

append `1234567890` at [L62](https://github.com/healeycodes/coolrule/blob/main/src/parser.rs#L62) should fix the issue.

**Comment by healeycodes** [comment]
thanks for the report @logust79 

would you like to open a PR with the fix and a test?

**Comment by logust79** [comment]
Thank you. Will do :)

**Comment by healeycodes** [comment]
Fixed by https://github.com/healeycodes/coolrule/pull/2
